#  Sharing options at the bottom of the post.
#  Icons from <https://fontawesome.com/>

platforms:
  - type: Facebook
    icon: "fab fa-facebook-square"
    link: "https://www.facebook.com/sharer/sharer.php?title=TITLE&u=URL"

  - type: Reddit
    icon: "fa-brands fa-square-reddit"
    link: "https://www.reddit.com/submit?url=URL&title=TITLE"

  - type: Linkedin
    icon: "fab fa-linkedin"
    link: "https://www.linkedin.com/feed/?shareActive=true&shareUrl=URL"

  - type: Telegram
    icon: "fab fa-telegram"
    link: "https://t.me/share/url?url=URL&text=TITLE"

  - type: Twitter
    icon: "fa-brands fa-square-x-twitter"
    link: "https://twitter.com/intent/tweet?text=TITLE&url=URL"
