name: Image Optimizer
author: David Varghese
description: Action to Optimize Images

inputs:
  IMG_PATH:
    description: Path to the directory that contains the images
    required: true
  ASSETS_BASE_PATH:
    description: Base path to the directory that stores the optimized images
    required: true

runs:
  using: composite
  steps:
    - name: Install Optimize Tools
      id: install-optimize-tools
      shell: bash
      run: |
        sudo apt-get update \
        && sudo apt-get install -y pngquant jpegoptim

        URL=$(
          curl -s https://api.github.com/repos/oxipng/oxipng/releases/latest \
          | grep browser_download_url \
          | grep 'amd64.deb"' \
          | cut -d '"' -f 4
        )
        curl -L "$URL" -o oxipng.deb
        sudo dpkg -i oxipng.deb

    - name: Run Optimize Script
      id: run-optimize-script
      shell: bash
      run: ${{ github.action_path }}/optimize.sh "${{ inputs.IMG_PATH }}" "${{ inputs.ASSETS_BASE_PATH }}"
