name: Deploy Source Code to Cloudflare
run-name: Deploy to Cloudflare by @${{ github.actor }}

on:
  push:
    branches: [main]

jobs:
  source-code:
    name: Source Code Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Chirpy
        id: checkout-chirpy
        uses: actions/checkout@v4
        with:
          repository: cotes2020/chirpy-starter
          path: chirpy
      - name: Checkout Repository
        id: checkout-repository
        uses: actions/checkout@v4
        with:
          submodules: true
          path: main
      - name: Build Source Code
        id: build-source-code
        uses: ./main/.github/actions/cloudflare-publish
        with:
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
      - name: Cloudflare Deploy
        id: cloudflare-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy chirpy/_site --project-name=my-source-code
